name: PGE22
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anaconda_prompt=1.1.0=haa95532_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - expat=2.6.4=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.16=h3f729d1_0
  - pip=25.0=py312haa95532_0
  - python=3.12.9=h14ffc60_0
  - setuptools=75.8.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - altgraph==0.17.4
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachelib==0.13.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - faiss-cpu==1.10.0
      - filelock==3.18.0
      - flask==3.1.0
      - flask-cors==5.0.1
      - flask-session==0.8.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.23
      - langchain-community==0.3.21
      - langchain-core==0.3.51
      - langchain-huggingface==0.1.2
      - langchain-mistralai==0.2.10
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.28
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - msgspec==0.19.0
      - multidict==6.4.2
      - mypy-extensions==1.0.0
      - mysql==0.0.3
      - mysql-connector==2.2.9
      - mysqlclient==2.2.7
      - networkx==3.4.2
      - nuitka==2.6.9
      - numpy==2.2.4
      - openai==1.73.0
      - ordered-set==4.1.0
      - orjson==3.10.16
      - packaging==24.2
      - pandas==2.2.3
      - pefile==2023.2.7
      - pillow==11.2.1
      - propcache==0.3.1
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydantic-settings==2.8.1
      - pyinstaller==6.12.0
      - pyinstaller-hooks-contrib==2025.2
      - pymysql==1.1.1
      - pypdf2==3.0.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pywin32-ctypes==0.2.3
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==4.0.2
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.40
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.51.2
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - yarl==1.19.0
      - zstandard==0.23.0
prefix: C:\Users\louis\anaconda3\envs\PGE22
